# Tests for the presence of files in the workspace

Feature: Workspace files

    As a researcher,
    I want to make sure that my workflow produces the expected files,
    and that the relevant input files are present in the workspace,
    so that I can be sure that the workflow outputs are correct.

    Scenario: The workspace contains all the relevant input files
        When the workflow execution completes
        Then the workspace should contain "skim.cxx"
        And the workspace should include "histograms.py"
        And the workspace should include "plot.py"

    Scenario: The expected plots are present in the workspace
        When the workflow is finished
        Then the workspace should include "jphi_1.png"
        And the workspace should include "jphi_2.pdf"
        And the workspace should include "jphi_2.png"
        And the workspace should include "jeta_2.pdf"
        And the workspace should include "jeta_2.png"
        And the workspace should include "pt_vis.pdf"
        And the workspace should include "pt_vis.png"
        And the workspace should include "jm_1.pdf"
        And the workspace should include "jm_1.png"
        And the workspace should include "jbtag_2.pdf"
        And the workspace should include "jbtag_2.png"
        And the workspace should include "jm_2.pdf"
        And the workspace should include "jm_2.png"
        And the workspace should include "phi_met.pdf"
        And the workspace should include "phi_met.png"
        And the workspace should include "m_vis.pdf"
        And the workspace should include "m_vis.png"
        And the workspace should include "q_2.pdf"
        And the workspace should include "q_2.png"
        And the workspace should include "q_1.pdf"
        And the workspace should include "q_1.png"
        And the workspace should include "pt_met.pdf"
        And the workspace should include "pt_met.png"
        And the workspace should include "eta_1.pdf"
        And the workspace should include "eta_1.png"
        And the workspace should include "eta_2.pdf"
        And the workspace should include "eta_2.png"
        And the workspace should include "jbtag_1.pdf"
        And the workspace should include "jbtag_1.png"
        And the workspace should include "njets.pdf"
        And the workspace should include "njets.png"
        And the workspace should include "iso_1.pdf"
        And the workspace should include "iso_1.png"
        And the workspace should include "phi_1.pdf"
        And the workspace should include "phi_1.png"
        And the workspace should include "dm_2.pdf"
        And the workspace should include "dm_2.png"
        And the workspace should include "phi_2.pdf"
        And the workspace should include "phi_2.png"
        And the workspace should include "mt_2.pdf"
        And the workspace should include "mt_2.png"
        And the workspace should include "mt_1.pdf"
        And the workspace should include "mt_1.png"
        And the workspace should include "jeta_1.pdf"
        And the workspace should include "jeta_1.png"
        And the workspace should include "jpt_1.pdf"
        And the workspace should include "jpt_1.png"
        And the workspace should include "pt_1.pdf"
        And the workspace should include "pt_1.png"
        And the workspace should include "mjj.pdf"
        And the workspace should include "mjj.png"
        And the workspace should include "pt_2.pdf"
        And the workspace should include "pt_2.png"
        And the workspace should include "npv.pdf"
        And the workspace should include "npv.png"
        And the workspace should include "jpt_2.pdf"
        And the workspace should include "jpt_2.png"
        And the workspace should include "m_2.pdf"
        And the workspace should include "m_2.png"
        And the workspace should include "m_1.pdf"
        And the workspace should include "m_1.png"
        And the workspace should include "jdeta.pdf"
        And the workspace should include "jdeta.png"
        And the workspace should include "ptjj.pdf"
        And the workspace should include "ptjj.png"
        And the workspace should include "iso_2.pdf"
        And the workspace should include "iso_2.png"

